export default Object.freeze({
    INIT_GAME: 'INIT_GAME',
    CHANGE_MOVE: 'CHANGE_MOVE',
    CLEAR_GAME: 'CLEAR_GAME',
    CAN_MOVE_FIELDS: 'CAN_MOVE_FIELDS',
    CLEAR_MOVE_FIELDS: 'CLEAR_MOVE_FIELDS',
    SET_FIGURE_ON_BOARD: 'SET_FIGURE_ON_BOARD',
    REMOVE_FIGURE_ON_BOARD: 'REMOVE_FIGURE_ON_BOARD',
    MOVE_FIGURE: 'MOVE_FIGURE',
    TO_IDENTIFY_POSSIBLE_MOVES: 'TO_IDENTIFY_POSSIBLE_MOVES',
    SET_ACTIVE_FIGURE: 'SET_ACTIVE_FIGURE'
});
